apiVersion: v1
kind: Service
metadata:
  name: orders-mongodb
  labels:
    app: orders
  namespace: micro
spec:
  ports:
    - port: 27017
  selector:
    app: orders
    tier: orders
  clusterIP: None