apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders
  labels:
    app: orders
  namespace: micro
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi